### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jiadong-deng** [trumpetx/UNetVRTK#1]
NullReferenceException: Object reference not set to an instance of an objectWizardArena.PlayerUpdater.Update () (at Assets/UNetVRTK/Scripts/PlayerUpdater.cs:87)
help me please!

**Comment by trumpetx** [comment]
In my own personal project I actually ran into something similar and fixed it differently, but the reason is because of a timing issue in starting up.  Update() happens before the controllers are assigned.  In this case, it's easy enough to check those controllers for null in the Update() loop.  I've gone ahead and made the change.  Git pull the latest or simply put in the null checks yourself:

```
        void Update()
        {
            if (isLocalPlayer && leftController != null && rightController != null)
            {
                    leftControllerRender.position = leftController.position;
                    rightControllerRender.position = rightController.position;
                    headRender.position = head.position;
                    leftControllerRender.rotation = leftController.rotation;
                    rightControllerRender.rotation = rightController.rotation;
                    headRender.rotation = head.rotation;
            }
        }
```

Let me know if that doesn't work for you.
